services:
  db:
    container_name: fastfeet-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fastfeet-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
